server:
  port: 8080
  error:
    include-message: always

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_KEY}
            scope:
              - email
              - profile
            redirect-uri: "https://4abc-115-90-99-121.ngrok-free.app/login/oauth2/code/google"
  servlet:
    multipart:
      max-file-size: 5MB
