GET http://localhost:8080/items

### 상세조회
GET http://localhost:8080/items/2

### 상품등록
POST http://localhost:8080/items
Authorization: eyJraWQiOiJrZXkxIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJ0ZXN0MUBuYXZlci5jb20iLCJpYXQiOjE3NDgzMjg0MDcsImV4cCI6MTc0ODQ3MjQwN30.8ogk9-YbvQLXZbHvzE7zi5HJ53QNj1-TZS3yZa75AZY
Content-Type: application/json

{
  "name":"생성",
  "description": "test",
  "imageUrl": ""
}

### 리플조회
GET http://localhost:8080/reply/item/42
