### 로그인
# @name login_2fa
POST http://localhost:8080/login
Content-Type: application/json

{
  "email":"test1@naver.com",
  "password": 123456
}
> {%
    if (response.body && response.body.data) {
        client.global.set("authToken", response.body.data.token)
    } else {
        client.global.set("authToken", "")
    }
%}

### 좋아요
POST http://localhost:8080/likes
Authorization: {{authToken}}
Content-Type: application/json

{
  "itemId": 1
}

### 상세조회 로그인
GET http://localhost:8080/items
Authorization: {{authToken}}

### 유저정보 상세조회
GET http://localhost:8080/member/info
Authorization: {{authToken}}

