### 로그인
# @name login_2fa
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": 123456
}
> {%
    if (response.body && response.body.data) {
        client.global.set("authToken", response.body.data.token)
    } else {
        client.global.set("authToken", "")
    }
%}

### 멤버 정보 수정
PUT http://localhost:8080/member/info
Authorization: {{authToken}}
Content-Type: application/json

{
  "profileImage": "https://gnews.gg.go.kr/OP_UPDATA/UP_DATA/_FILEZ/202112/20211227054431183687488.jpg",
  "profileMessage": "어흥",
  "nickname": "호랑이"
}

### 멤버 정보 조회
GET http://localhost:8080/member/info
Authorization: {{authToken}}
Content-Type: application/json

### 멤버 정보 memberid로 조회
GET http://localhost:8080/member/1
Content-Type: application/json