### 로그인
# @name login_2fa
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": 123456
}
> {%
    if (response.body && response.body.data) {
        client.global.set("authToken", response.body.data.token)
    } else {
        client.global.set("authToken", "")
    }
%}

### 전체조회
GET http://localhost:8080/items

### 상세조회
GET http://localhost:8080/items/2

### 상품등록
POST http://localhost:8080/items
Authorization: {{authToken}}
Content-Type: application/json

{
  "name": "테스트",
  "description": "test",
  "price": 100,
  "imageUrl": "",
  "reaction1": true,
  "reaction2": true,
  "reaction3": false,
  "reaction4": true,
  "reaction5": false,
  "reaction6": false,
  "reaction7": true,
  "reaction8": false,
  "reaction9": true
}

### 상품삭제
DELETE http://localhost:8080/items/47
Authorization: {{authToken}}
Content-Type: application/json

### 상품수정
PUT http://localhost:8080/items/47
Authorization: {{authToken}}
Content-Type: application/json

{
  "name": "상품 수정 테스트",
  "description": "test modify",
  "price": 777,
  "imageUrl": ""
}

### 멤버가 작성한 글 전체조회
GET http://localhost:8080/items/member/1

### 랭킹
GET http://localhost:8080/items/rank