### 로그인
# @name login_2fa
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": 123456
}
> {%
    if (response.body && response.body.data) {
        client.global.set("authToken", response.body.data.token)
    } else {
        client.global.set("authToken", "")
    }
%}


### 레스토랑 리스트 생성
POST http://localhost:8080/restaurants-list
Authorization: {{authToken}}
Content-Type: application/json

{
  "title" : "비공개 맛집!",
  "description" : "설명",
  "isPublic" : false
}

### 내가 작성한 레스토랑 리스트 조회
GET http://localhost:8080/restaurants-list/my
Authorization: {{authToken}}
Content-Type: application/json

### 공개 레스토랑 리스트 조회
GET http://localhost:8080/restaurants-list
Content-Type: application/json

### 수정할 레스토랑 리스트 조회
GET http://localhost:8080/restaurants-list/info/1
Authorization: {{authToken}}
Content-Type: application/json


### 레스토랑 리스트 수정
PUT http://localhost:8080/restaurants-list/info
Authorization: {{authToken}}
Content-Type: application/json

{
  "id": 1,
  "title": "혜화 맛집",
  "description": "제순식당, 오레노카츠, 칸다소바 등등",
  "isPublic": true
}

### 작성한 리스트 삭제
DELETE http://localhost:8080/restaurants-list/11
Authorization: {{authToken}}
Content-Type: application/json

### 리스트 내 전체 식당 보기 - 비공개 리스트
GET http://localhost:8080/restaurants-list/12/restaurants
Authorization: {{authToken}}
Content-Type: application/json

### 리스트 내 전체 식당 보기 - 공개 리스트
GET http://localhost:8080/restaurants-list/1/restaurants
Content-Type: application/json

### 리스트에 식당 등록하기
POST http://localhost:8080/restaurants-list/8/restaurants
Authorization: {{authToken}}
Content-Type: application/json

{
  "name": "봉심식당",
  "description": "골목에 숨겨진 양식 맛집",
  "address": "서울특별시 종로구 명륜4가 대학로11길 38-10 봉심식당 1층",
  "imageUrl": "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nrs7F8wk0Z6DHrBMQ5kNJNji7twpfRU8VfHSRIFr8VPelf3jsXOklY-_d1m7-O9qzQlSW4NPHOkdnsg7ASGWZ4JQvUIU4NwnP_t05ScDKUzmlt5NbU3L-KJq2G4RDABdxRhpWHj=s1360-w1360-h1020-rw",
  "detailList": [
    {
      "name": "알리오올리오",
      "price": 14000,
      "imageUrl" : "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nplTpm50UnJu034WYs9szUX0sDA98T758VcQnAYdx8LH80R7Ak4riKBPC5IuzXoZbxIN2G6S_30sPgfu12-kCMRbOcpH5Op1EqkfFYpZhCLsR0cz9QdWnQaecJ19NvjnUznmRYR2g=s1360-w1360-h1020-rw",
      "description" : "마늘향이 아주 깊게 난다. 바디감 훌륭한 알리오올리오"
    },
    {
      "name": "뇨끼",
      "price": 16000,
      "imageUrl" : "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nplTpm50UnJu034WYs9szUX0sDA98T758VcQnAYdx8LH80R7Ak4riKBPC5IuzXoZbxIN2G6S_30sPgfu12-kCMRbOcpH5Op1EqkfFYpZhCLsR0cz9QdWnQaecJ19NvjnUznmRYR2g=s1360-w1360-h1020-rw",
      "description" : "쫀득 뇨끼 환상적인 맛"
    },
    {
      "name": "스테이크",
      "price": 26000,
      "imageUrl" : "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nra1YU_Dii4vL-WTq9pgUYE1Yrw6shpKHO3OHRCXFHdUHx3Xs37Ocvu2V9OR0fJL-FL5SUGqiF9mbkb16l0bD4GFtylm_kXrfyXTclRqSAocErfjEqe0pbrLEPNanrsKciUHdc=s1360-w1360-h1020-rw",
      "description" : "부드러운 식감의 스테이크. 밑간도 훌륭하다"
    }
  ]
}

### 리스트에 등록한 식당 삭제하기
DELETE http://localhost:8080/restaurants-list/restaurant/6
Authorization: {{authToken}}
Content-Type: application/json

### 리스트에 등록한 식당 수정하기
PUT http://localhost:8080/restaurants-list/restaurant/5
Authorization: {{authToken}}
Content-Type: application/json

{
  "name": "제순식당",
  "address": "혜화 번화가 골목 어딘가",
  "description": "제육도 순두부찌개도 맛있다.",
  "imageUrl": "몰라"
}

### 등록된 식당 자세히 보기 - 공개
GET http://localhost:8080/restaurants-list/restaurant/3
Content-Type: application/json

### 등록된 식당 자세히 보기 - 비공개
GET http://localhost:8080/restaurants-list/restaurant/4
Authorization: {{authToken}}
Content-Type: application/json


### 등록한 식당 상세내용 수정하기
PUT http://localhost:8080/restaurants-list/restaurant/info
Authorization: {{authToken}}
Content-Type: application/json

{
  "list": [
    {
      "id": 22,
      "name": "알리오올리오",
      "price": 14000,
      "imageUrl" : "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nplTpm50UnJu034WYs9szUX0sDA98T758VcQnAYdx8LH80R7Ak4riKBPC5IuzXoZbxIN2G6S_30sPgfu12-kCMRbOcpH5Op1EqkfFYpZhCLsR0cz9QdWnQaecJ19NvjnUznmRYR2g=s1360-w1360-h1020-rw",
      "description" : "마늘향이 아주 깊게 난다. 바디감 훌륭한 알리오올리오"
    },
    {
      "id": 23,
      "name": "뇨끼",
      "price": 16000,
      "imageUrl" : "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nplTpm50UnJu034WYs9szUX0sDA98T758VcQnAYdx8LH80R7Ak4riKBPC5IuzXoZbxIN2G6S_30sPgfu12-kCMRbOcpH5Op1EqkfFYpZhCLsR0cz9QdWnQaecJ19NvjnUznmRYR2g=s1360-w1360-h1020-rw",
      "description" : "쫀득 뇨끼 환상적인 맛"
    },
    {
      "id": 24,
      "name": "스테이크",
      "price": 26000,
      "imageUrl" : "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nra1YU_Dii4vL-WTq9pgUYE1Yrw6shpKHO3OHRCXFHdUHx3Xs37Ocvu2V9OR0fJL-FL5SUGqiF9mbkb16l0bD4GFtylm_kXrfyXTclRqSAocErfjEqe0pbrLEPNanrsKciUHdc=s1360-w1360-h1020-rw",
      "description" : "부드러운 식감의 스테이크. 밑간도 훌륭하다"
    }
  ]
}